### ISSUE TITLE
How it was supposed to work ?

### ISSUE THREAD

**Issue by Aviksaikat** [arnetheduck/nim-varroa#1]
Hi, I was looking at this repo & I'm curious about your thought process for this project. How it was supposed to work and how it's different from the actual bee client you can tell me

**Comment by arnetheduck** [comment]
* a learning experiment to understand the protocol better, and see what its properties are with a non-standard client, ie what a non-standard client can do by behaving differently than bee
* a library for accessing swarm content from low-powered devices (using the infrastructure developed for nimbus)
* a client that can manage the equivalent of multiple bee instances in one program instance (so you don't have to run lots of services)

Pick any ;)

**Comment by Aviksaikat** [comment]
So basically a light version of the actual bee client & you took the basic functionalities only?

**Comment by arnetheduck** [comment]
yes

**Comment by Aviksaikat** [comment]
I'm making something similar in `C++` can you tell me how should I get started? I have gone through the actual client & it's very vast and messy.  If you can help me with anything that would be super helpful

**Comment by arnetheduck** [comment]
>  I have gone through the actual client

this is how I did it, I don't know of any better ways but I have also not looked for them -good luck!
